name: flutter_common_classes
description: "A new Flutter package project."
version: 1.0.10
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.1
  confirm_alert: ^0.0.1
  dropdown_search: ^6.0.2
  faker: ^2.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_flavor: ^3.1.4
  flutter_secure_storage: ^9.2.4
  form_builder_dropdown_search:
    git:
      url: https://github.com/alexsosat/form_builder_dropdown_search.git
      ref: 0.0.4
  fpdart: ^1.1.1
  internet_connection_checker_plus: ^2.7.2
  intl: any
  logger: ^2.6.1
  lottie: ^3.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  generate: true
# To add assets to your package, add an assets section, like this:
assets:
  - assets/animations/failure/
# For details regarding assets in packages, see
# https://flutter.dev/to/asset-from-package
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/to/resolution-aware-images
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/to/font-from-package
flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: FlutterCommonLocalizations # Optional. Sets the name for the generated localization class. Default: S
  main_locale: es # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
  arb_dir: assets/l10n # Optional. Sets the directory of your ARB resource files. Provided value should be a valid path on your system. Default: lib/l10n
  output_dir: lib/localization # Optional. Sets the directory of generated localization files. Provided value should be a valid path on your system. Default: lib/generated
  use_deferred_loading: false # Optional. Must be set to true to generate localization code that is loaded with deferred loading. Default: false
